version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
#    command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    environment:
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_DB=${REDIS_DB}
    env_file:
      - ".env"
    volumes:
      - cache:/data


volumes:
  cache: { }