# Generated by Django 5.0.3 on 2024-03-28 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_on_top_alter_article_visible'),
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grading',
            new_name='Grade',
        ),
    ]
