# Generated by Django 5.0.3 on 2024-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.BooleanField(default=False),
        ),
    ]
