# Generated by Django 5.0.3 on 2024-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('facebook', 'facebook'), ('email', 'email')], default='email', max_length=10),
        ),
    ]
