# Generated by Django 5.0.3 on 2024-03-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_otp_expiry_user_vendor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
