# Generated by Django 5.0.3 on 2024-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restore_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
