# Generated by Django 5.0.3 on 2024-04-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_category', models.CharField(max_length=100)),
                ('it_category', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='original_content',
            new_name='en_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='original_title',
            new_name='en_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='translated_content',
            new_name='it_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='translated_title',
            new_name='it_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='slider',
            name='big_image',
            field=models.ImageField(upload_to='slider_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='article.articleimage'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='article.tag'),
        ),
    ]
