# Generated by Django 5.0.3 on 2024-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
