# Generated by Django 5.0.3 on 2024-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articleimage_tag_remove_article_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
