# Generated by Django 5.0.3 on 2024-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_category_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='original_category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='original_category',
        ),
        migrations.AddField(
            model_name='category',
            name='translated_category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
