# Generated by Django 5.0.3 on 2024-04-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_category_article_original_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='original_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='original_content',
            new_name='en_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='original_title',
            new_name='en_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='translated_content',
            new_name='it_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='translated_title',
            new_name='it_title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='original_category',
            new_name='en_category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='translated_category',
            new_name='it_category',
        ),
    ]
