# Generated by Django 5.0.3 on 2024-04-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_userurlviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='view_count',
        ),
    ]
