# Generated by Django 5.0.3 on 2024-04-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_article_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='en_content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='it_content',
            field=models.JSONField(),
        ),
    ]
