# Generated by Django 5.0.3 on 2024-04-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_userurlviewer'),
        ('article', '0008_alter_article_en_content_alter_article_it_content'),
    ]

    operations = [
    ]
