# Generated by Django 5.0.3 on 2024-04-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_userurlviewer_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurlviewer',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userurlviewer',
            name='ip',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
