# Generated by Django 5.0.3 on 2024-04-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_merge_20240419_1732'),
        ('article', '0010_alter_userurlviewer_article_alter_userurlviewer_ip'),
    ]

    operations = [
    ]
